"""init

Revision ID: 0a9f881896a6
Revises: e4a21a917048
Create Date: 2026-01-01 19:26:56.197275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a9f881896a6'
down_revision: Union[str, Sequence[str], None] = 'e4a21a917048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('tech_role', postgresql.ENUM('MEMBER', 'ORGANIZER', 'MANAGER', 'ADMIN', name='userrole'), nullable=True))
    op.drop_column('Users', 'techRole')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('techRole', postgresql.ENUM('MEMBER', 'ORGANIZER', 'MANAGER', 'ADMIN', name='userrole'), autoincrement=False, nullable=True))
    op.drop_column('Users', 'tech_role')
    # ### end Alembic commands ###
