"""init

Revision ID: 1700db77f2a5
Revises: e076dfc32787
Create Date: 2025-12-30 00:39:38.668292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1700db77f2a5'
down_revision: Union[str, Sequence[str], None] = 'e076dfc32787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Speakers', sa.Column('full_name', sa.String(), nullable=False))
    op.drop_column('Speakers', 'full_mame')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Speakers', sa.Column('full_mame', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Speakers', 'full_name')
    # ### end Alembic commands ###
