"""init

Revision ID: 54c4a7f50911
Revises: 
Create Date: 2025-12-29 18:36:30.444910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c4a7f50911'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('FUTURE', 'CURRENT', 'STARTED', 'ENDED', name='eventstatus'), nullable=True),
    sa.Column('irlMeetingSpace', sa.String(), nullable=True),
    sa.Column('onlineMeetingSpace', sa.String(), nullable=True),
    sa.Column('streamLink', sa.String(), nullable=True),
    sa.Column('coverUrl', sa.String(), nullable=True),
    sa.Column('registrationLink', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('photoURL', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EventSpeakers',
    sa.Column('eventId', sa.Integer(), nullable=False),
    sa.Column('speakerId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['eventId'], ['Events.id'], ),
    sa.ForeignKeyConstraint(['speakerId'], ['Speakers.id'], ),
    sa.PrimaryKeyConstraint('eventId', 'speakerId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EventSpeakers')
    op.drop_table('Speakers')
    op.drop_table('Events')
    # ### end Alembic commands ###
