"""init

Revision ID: 890d0e299537
Revises: 44fb4709f202
Create Date: 2026-01-01 16:28:34.829088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890d0e299537'
down_revision: Union[str, Sequence[str], None] = '44fb4709f202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('tech_role', sa.Enum('MEMBER', 'ORGANIZER', 'MANAGER', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('club_role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('DeliveryJob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'TELEGRAM', 'PLATFORM', name='deliverychannel'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', name='deliverystatus'), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EventNotifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('EVENT_CREATED', 'EVENT_UPDATED', 'EVENT_START_SOON', 'EVENT_STARTED', 'EVENT_ENDED', 'ADDED_AS_MANAGER', 'ADDED_AS_ORGANIZER', 'ADDED_AS_MEMBER', 'REMOVED_AS_MANAGER', 'REMOVED_AS_ORGANIZER', 'NEW_COMMENT', 'ANALYTICS_REPORT_READY', name='notificationtype'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EventNotifications')
    op.drop_table('DeliveryJob')
    op.drop_table('Users')
    # ### end Alembic commands ###
