"""init models

Revision ID: aed5f251a6a5
Revises: dd6032f17766
Create Date: 2026-01-19 14:21:03.963533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aed5f251a6a5'
down_revision: Union[str, Sequence[str], None] = 'dd6032f17766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('FUTURE', 'CURRENT', 'STARTED', 'ENDED', name='eventstatus'), nullable=True),
    sa.Column('irl_meeting_space', sa.String(), nullable=True),
    sa.Column('online_meeting_space', sa.String(), nullable=True),
    sa.Column('stream_link', sa.String(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('registration_link', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Speakers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('tech_role', postgresql.ENUM('MEMBER', 'ORGANIZER', 'MANAGER', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('club_role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('DeliveryJob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'TELEGRAM', 'PLATFORM', name='deliverychannel'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', name='deliverystatus'), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EventNotifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('EVENT_CREATED', 'EVENT_UPDATED', 'EVENT_START_SOON', 'EVENT_STARTED', 'EVENT_ENDED', 'ADDED_AS_MANAGER', 'ADDED_AS_ORGANIZER', 'ADDED_AS_MEMBER', 'REMOVED_AS_MANAGER', 'REMOVED_AS_ORGANIZER', 'NEW_COMMENT', 'ANALYTICS_REPORT_READY', name='notificationtype'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EventSpeakers',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['Events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['Speakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'speaker_id')
    )
    op.create_table('Invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('MEMBER', 'ORGANIZER', 'MANAGER', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('invited_by_id', sa.Integer(), nullable=True),
    sa.Column('used_by_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['Users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_by_id'], ['Users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Invites_token'), 'Invites', ['token'], unique=True)
    op.create_table('RefreshToken',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RefreshToken_user_id'), 'RefreshToken', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_RefreshToken_user_id'), table_name='RefreshToken')
    op.drop_table('RefreshToken')
    op.drop_index(op.f('ix_Invites_token'), table_name='Invites')
    op.drop_table('Invites')
    op.drop_table('EventSpeakers')
    op.drop_table('EventNotifications')
    op.drop_table('DeliveryJob')
    op.drop_table('Users')
    op.drop_table('Speakers')
    op.drop_table('Events')
    # ### end Alembic commands ###
