"""init

Revision ID: b26998a913c7
Revises: f4f5035b0fb9
Create Date: 2025-12-29 23:25:23.948345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26998a913c7'
down_revision: Union[str, Sequence[str], None] = 'f4f5035b0fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('EventSpeakers_eventId_fkey'), 'EventSpeakers', type_='foreignkey')
    op.drop_constraint(op.f('EventSpeakers_speakerId_fkey'), 'EventSpeakers', type_='foreignkey')
    op.create_foreign_key(None, 'EventSpeakers', 'Events', ['eventId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'EventSpeakers', 'Speakers', ['speakerId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'EventSpeakers', type_='foreignkey')
    op.drop_constraint(None, 'EventSpeakers', type_='foreignkey')
    op.create_foreign_key(op.f('EventSpeakers_speakerId_fkey'), 'EventSpeakers', 'Speakers', ['speakerId'], ['id'])
    op.create_foreign_key(op.f('EventSpeakers_eventId_fkey'), 'EventSpeakers', 'Events', ['eventId'], ['id'])
    # ### end Alembic commands ###
