"""init

Revision ID: e076dfc32787
Revises: b26998a913c7
Create Date: 2025-12-30 00:29:49.671404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e076dfc32787'
down_revision: Union[str, Sequence[str], None] = 'b26998a913c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventSpeakers', sa.Column('event_id', sa.Integer(), nullable=False))
    op.add_column('EventSpeakers', sa.Column('speaker_id', sa.Integer(), nullable=False))
    op.add_column('EventSpeakers', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('EventSpeakers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('EventSpeakers_speakerId_fkey'), 'EventSpeakers', type_='foreignkey')
    op.drop_constraint(op.f('EventSpeakers_eventId_fkey'), 'EventSpeakers', type_='foreignkey')
    op.create_foreign_key(None, 'EventSpeakers', 'Events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'EventSpeakers', 'Speakers', ['speaker_id'], ['id'], ondelete='CASCADE')
    op.drop_column('EventSpeakers', 'updatedAt')
    op.drop_column('EventSpeakers', 'speakerId')
    op.drop_column('EventSpeakers', 'eventId')
    op.drop_column('EventSpeakers', 'createdAt')
    op.add_column('Events', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('Events', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Events', sa.Column('irl_meeting_space', sa.String(), nullable=True))
    op.add_column('Events', sa.Column('online_meeting_space', sa.String(), nullable=True))
    op.add_column('Events', sa.Column('stream_link', sa.String(), nullable=True))
    op.add_column('Events', sa.Column('cover_url', sa.String(), nullable=True))
    op.add_column('Events', sa.Column('registration_link', sa.String(), nullable=False))
    op.add_column('Events', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Events', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('Events', 'startDate')
    op.drop_column('Events', 'registrationLink')
    op.drop_column('Events', 'onlineMeetingSpace')
    op.drop_column('Events', 'irlMeetingSpace')
    op.drop_column('Events', 'endDate')
    op.drop_column('Events', 'coverUrl')
    op.drop_column('Events', 'streamLink')
    op.drop_column('Events', 'updatedAt')
    op.drop_column('Events', 'createdAt')
    op.add_column('Speakers', sa.Column('full_mame', sa.String(), nullable=False))
    op.add_column('Speakers', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('Speakers', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Speakers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('Speakers', 'updatedAt')
    op.drop_column('Speakers', 'createdAt')
    op.drop_column('Speakers', 'photoURL')
    op.drop_column('Speakers', 'fullName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Speakers', sa.Column('fullName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Speakers', sa.Column('photoURL', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Speakers', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('Speakers', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('Speakers', 'updated_at')
    op.drop_column('Speakers', 'created_at')
    op.drop_column('Speakers', 'photo_url')
    op.drop_column('Speakers', 'full_mame')
    op.add_column('Events', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('Events', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('Events', sa.Column('streamLink', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Events', sa.Column('coverUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Events', sa.Column('endDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('Events', sa.Column('irlMeetingSpace', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Events', sa.Column('onlineMeetingSpace', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Events', sa.Column('registrationLink', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Events', sa.Column('startDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('Events', 'updated_at')
    op.drop_column('Events', 'created_at')
    op.drop_column('Events', 'registration_link')
    op.drop_column('Events', 'cover_url')
    op.drop_column('Events', 'stream_link')
    op.drop_column('Events', 'online_meeting_space')
    op.drop_column('Events', 'irl_meeting_space')
    op.drop_column('Events', 'end_date')
    op.drop_column('Events', 'start_date')
    op.add_column('EventSpeakers', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('EventSpeakers', sa.Column('eventId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('EventSpeakers', sa.Column('speakerId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('EventSpeakers', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'EventSpeakers', type_='foreignkey')
    op.drop_constraint(None, 'EventSpeakers', type_='foreignkey')
    op.create_foreign_key(op.f('EventSpeakers_eventId_fkey'), 'EventSpeakers', 'Events', ['eventId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('EventSpeakers_speakerId_fkey'), 'EventSpeakers', 'Speakers', ['speakerId'], ['id'], ondelete='CASCADE')
    op.drop_column('EventSpeakers', 'updated_at')
    op.drop_column('EventSpeakers', 'created_at')
    op.drop_column('EventSpeakers', 'speaker_id')
    op.drop_column('EventSpeakers', 'event_id')
    # ### end Alembic commands ###
