"""init

Revision ID: f2557250b8b8
Revises: fc69b43724a2
Create Date: 2026-01-01 18:04:14.777630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2557250b8b8'
down_revision: Union[str, Sequence[str], None] = 'fc69b43724a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Invites', sa.Column('role', sa.Enum('MEMBER', 'ORGANIZER', 'MANAGER', 'ADMIN', name='userrole'), nullable=True))
    op.add_column('Users', sa.Column('techRole', postgresql.ENUM('MEMBER', 'ORGANIZER', 'MANAGER', 'ADMIN', name='userrole'), nullable=True))
    op.drop_column('Users', 'tech_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('tech_role', postgresql.ENUM('MEMBER', 'ORGANIZER', 'MANAGER', 'ADMIN', name='userrole'), autoincrement=False, nullable=True))
    op.drop_column('Users', 'techRole')
    op.drop_column('Invites', 'role')
    # ### end Alembic commands ###
