"""init

Revision ID: fc69b43724a2
Revises: 890d0e299537
Create Date: 2026-01-01 17:48:15.977134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fc69b43724a2'
down_revision: Union[str, Sequence[str], None] = '890d0e299537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


user_role_enum = postgresql.ENUM('MEMBER', 'ORGANIZER', 'MANAGER', 'ADMIN', name='userrole')
user_role_enum.create(op.get_bind(), checkfirst=True)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=True),
    sa.Column('used_by_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['Users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_by_id'], ['Users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Invites_token'), 'Invites', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Invites_token'), table_name='Invites')
    op.drop_table('Invites')
    # ### end Alembic commands ###
